---
- name: Install the php & mariad
  hosts: all
  become: true

  tasks:
    - name: Install the required packages
      dnf:
        name:
          - php
          - mariadb
        state: present

- name: Install RPM Dev tools and Update all packages
  hosts: all
  become: true

  tasks:
    - name: Install RPM development tools
      dnf:
        name: "@Development Tools"
        state: present


