---
- hosts: all
  become: true
  tasks:
     - name: Install Apache web server
       package:
          name: httpd
          state: present

     - name: Start and enable httpd
       service:
          name: httpd
          state: started
          enabled: yes


