---
- name: Create User account with developer as job description
  hosts: dev, test
  become: true

  tasks:
     - name: Create group devops
       group:
          name: devops
          state: present

     - name: Create users 
       user:
          name: "{{ item.name }}"
          password: "{{ PW_developer | password_hash('sha512') }}"
          groups: devops
       when: item.job == "developer"
       loop: "{{ myusers }}"

- name: Create User account with manager as job description
  hosts: prod
  become: true

  tasks:
     - name: Create group opsngr
       group:
          name: opsngr
          state: present

     - name: Create users 
       user:
          name: "{{ item.name }}"
          password: "{{ PW_developer | password_hash('sha512') }}"
          groups: devops
       when: item.job == "manager"
       loop: "{{ myusers }}"

  


  
